### ISSUE TITLE
Create Docker image

### ISSUE THREAD

**Issue by mdb** [vinyldns/vinyldns-cli#10]
Some users may find it beneficial to have the `vinyldns` CLI packaged as a Docker image. I'm imagining interaction like so:

```
docker run vinyldns/vinyldns-cli \
  --host="https://some-vinyldns.com" \
  --access-key="123" \
  --secret-key="456" \
  zones
```

**Comment by marekfilip** [comment]
Hi, I think the only option to pass an argument to container is by using environment variables.
Run command could work like this:

```
docker run vinyldns/vinyldns-cli \
  -e HOST="https://some-vinyldns.com" \
  -e ACCESS_KEY="123" \
  -e SECRET_KEY="456" \
  zones
```
