### ISSUE TITLE
Display record data for non-A, AAAA, CNAME record types 

### ISSUE THREAD

**Issue by rebstar6** [vinyldns/vinyldns-cli#17]
The vinyldns api supports all of the record types listed at https://www.vinyldns.io/api/recordset-model.html#record-data. Right now, the `record-set --zone-id <zoneID> --record-set-id <recordSetID>` command is only able to display the `Records` info for an A, AAAA, or CNAME type record. The info is empty for all other types, for example, this get on an NS gave me:

```
|------------------------------------------------|
| Account | system                               |
|------------------------------------------------|
| Created | 2018-10-01T14:31:24Z                 |
|------------------------------------------------|
| Status  | Active                               |
|------------------------------------------------|
| TTL     | 38400                                |
|------------------------------------------------|
| Zone    | d825a806-49ee-4c97-b010-daaed19b92c3 |
|------------------------------------------------|
| ID      | 6a367bd2-5dfe-42c3-a5aa-b5c424c1a6fe |
|------------------------------------------------|
| Type    | NS                                   |
|------------------------------------------------|
| Records |                                      |
|------------------------------------------------|
| Updated |                                      |
|------------------------------------------------|
| Name    | test.ok.                       |
|------------------------------------------------|
```

See the code at https://github.com/vinyldns/vinyldns-cli/blob/master/vinyldns.go#L713. This should be expanded to handle the fields for the following types:
- [ ] MX
- [ ] TXT
- [ ] PTR
- [ ] NS
- [ ] SOA
- [ ] SPF
- [ ] SSHFP

Note that each of these can be a separate PR, no need to pick up the whole thing at once :)

**Comment by tenpaiyomi** [comment]
@rebstar6 I've submitted a PR for the issue in question, as well as a full description of the logic of the code changes and my process for verification.  If there are any issues, please feel free to contact me and I would be more than happy to address them.
