### ISSUE TITLE
Fix required environment variables check

### ISSUE THREAD

**Issue by rebstar6** [vinyldns/vinyldns-cli#2]
The vinyldns CLI expects VINYLDNS_HOST, VINYLDNS_ACCESS_KEY, and VINYLDNS_SECRET_KEY to be set. But, validation checks for vinyldns_HOST, vinyldns_ACCESS_KEY, and vinyldns_SECRET_KEY.

This check needs to be updated at https://github.com/vinyldns/vinyldns-cli/blob/master/vinyldns.go#L686 so it is validating the correct variables

**Comment by invisiblethreat** [comment]
I'll grab this. I've written a library for just such an occasion.
