### ISSUE TITLE
Add info to the zones call

### ISSUE THREAD

**Issue by rebstar6** [vinyldns/vinyldns-cli#3]
In the list zones call, right now, only the zone ID and zone name are displayed. The vinyldns api returns a lot more information though that is currently dropped: https://www.vinyldns.io/api/list-zones.html

For this card, include the email, adminGroupId, adminGroupName, created, status, and updated fields. Note updated may be blank, in which case that can display empty for the zone.

**Comment by u5surf** [comment]
@rebstar6
Hi, I add more informations to the zone call.
but Zone structure don’t have the field of adminGroupName in the core package(https://github.com/vinyldns/go-vinyldns).
So I can send another PR to go-vinyldns to be additional this field. After adding it, I apply it in this repos.

**Comment by u5surf** [comment]
oh, I could not find out the field of AdminGroupName in zone-model from official API docs.
https://www.vinyldns.io/api/zone-model

**Comment by mdb** [comment]
@u5surf @rebstar6 Thanks so much for documenting this and attacking it! After some consideration, I'm leaning towards keeping the `zones` command light; I think I prefer it contain only an over view of all zones' `name` and `id` such that a user can get an easy-to-skim high level view, while keeping the `zone` response more detailed. Any opinions on this from you all?

**Comment by rebstar6** [comment]
thanks @u5surf, thats a docs issue, I made https://github.com/vinyldns/vinyldns/issues/260 to address the missing fields. You should still be seeing the adminGroupName coming back from the api.

@mdb fair, lets pull out `created`, `updated`, and `status` (those can just be on the single zone call), and maybe email. if it still looks too crazy, we can talk about the admin group stuff, but thats a pretty core vinyl feature, so it would be nice to have it in there
