### ISSUE TITLE
Add RecordSets search support

### ISSUE THREAD

**Issue by mitruly** [vinyldns/vinyldns-cli#82]
### Description
The VinylDNS API has been updated to include a new [global recordset search endpoint](https://www.vinyldns.io/api/list-recordsets-global.html) at `/recordsets`. This client should be updated to support this new endpoint.

**Comment by jagadeesh545** [comment]
@mitruly I would like to take up this issue.

**Comment by remerle** [comment]
@jagadeesh545 Have at it! We welcome your contribution!
